name: 发布到 GitHub Pages

on:
  push:
    branches:
      - main  # 或你用的主分支名

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取源码
        uses: actions/checkout@v4

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: 安装依赖
        run: pnpm install

      - name: 构建 Vite app
        run: pnpm build

      - name: 发布dist 到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
